In [17]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import joblib

In [18]:
df = pd.read_csv("../data/raw/ai4i2020.csv")

df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [19]:
print("Shape Before Processing:")
print(df.shape)

Shape Before Processing:
(10000, 14)

In [20]:
df = df.drop(
    columns=[
        'UDI',
        'Product ID',
        'TWF',
        'HDF',
        'PWF',
        'OSF',
        'RNF'
    ]
)

In [21]:
# Encode Machine Type

le = LabelEncoder()

df['Type'] = le.fit_transform(df['Type'])

df.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,2,298.1,308.6,1551,42.8,0,0
1,1,298.2,308.7,1408,46.3,3,0
2,1,298.1,308.5,1498,49.4,5,0
3,1,298.2,308.6,1433,39.5,7,0
4,1,298.2,308.7,1408,40.0,9,0

In [22]:
# Save Label Encoder

joblib.dump(
    le,
    "../models/label_encoder.pkl"
)

print("Label Encoder Saved")

Label Encoder Saved

In [23]:
# Define Features and Target

X = df.drop(
    columns=['Machine failure']
)

y = df['Machine failure']

print(X.shape)
print(y.shape)

(10000, 6)
(10000,)

In [24]:
# Train Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Shape:", X_train.shape)
print("Testing Shape :", X_test.shape)

Training Shape: (8000, 6)
Testing Shape : (2000, 6)

In [25]:
# Scaling

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [26]:
# Save Scaler

joblib.dump(
    scaler,
    "../models/scaler.pkl"
)

print("Scaler Saved")

Scaler Saved

In [27]:
# Check Output Shapes

print(X_train_scaled.shape)
print(X_test_scaled.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 6)
(2000, 6)
(8000,)
(2000,)

In [28]:
# Save Processed Data

processed_df = df.copy()

processed_df.to_csv(
    "../data/processed/processed_data.csv",
    index=False
)

print("Processed Data Saved")

Processed Data Saved

In [29]:
print(X.columns.tolist())

['Type', 'Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]']

In [30]:
print("Feature Engineering Completed")

Feature Engineering Completed